<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BuildingBlocks.ApiClients</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Clients\" />
    <None Remove="Extensions\" />
    <None Remove="Clients\Identity\" />
    <None Remove="Clients\Identity\Users\" />
    <None Remove="Clients\Identity\AccountDevice\" />
    <None Remove="Clients\Catalog\" />
    <None Remove="Clients\Catalog\Stores\" />
    <None Remove="Clients\Catalog\Stores\Models\" />
    <None Remove="Clients\Identity\Technicians\" />
    <None Remove="Clients\Identity\Technicians\Models\" />
    <None Remove="Clients\Catalog\UserStore\" />
    <None Remove="Clients\Catalog\UserStore\Models\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Clients\Identity\AccountDevice\" />
    <Folder Include="Clients\Catalog\Stores\" />
    <Folder Include="Clients\Catalog\Stores\Models\" />
    <Folder Include="Clients\Identity\Technicians\" />
    <Folder Include="Clients\Identity\Technicians\Models\" />
    <Folder Include="Clients\Catalog\UserStore\" />
    <Folder Include="Clients\Catalog\UserStore\Models\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
  </ItemGroup>
</Project>
