<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BuildingBlocks.EventBus</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\" />
    <None Remove="Events\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="Events\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.AmazonSQS" Version="8.3.6" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.2" />
  </ItemGroup>
</Project>
