<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\V1\" />
    <None Remove="Private\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\V1\" />
    <Folder Include="Private\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Authentication\Authentication.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\Loyalty.Application\Loyalty.Application.csproj" />
    <ProjectReference Include="..\Loyalty.Infrastructure\Loyalty.Infrastructure.csproj" />
    <ProjectReference Include="..\BuildingBlocks\CommonAuthorization\CommonAuthorization.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
