<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BuildingBlocks.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Persistence.Abstractions\Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\Authentication.Abstractions\Authentication.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Entities\" />
    <None Remove="Entities\Common\" />
    <None Remove="Extensions\" />
    <None Remove="Interceptors\" />
    <None Remove="Models\" />
    <None Remove="EntityFrameworkCore\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Entities\Common\" />
    <Folder Include="Extensions\" />
    <Folder Include="Interceptors\" />
    <Folder Include="Models\" />
    <Folder Include="EntityFrameworkCore\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.2.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
</Project>
